[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
	set laststatus=2
	let g:airline_powerline_fonts=1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#buffer_idx_mode = 1
	let g:airline#extensions#whitespace#mixed_indent_algo = 1
	let g:airline_theme = 'dark'
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
build = './install.sh nightly && yarn install'

# languages
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

